% -------------------------------------------------------------------
%  Generated by MATLAB on 18-Dec-2017 06:57:14
%  MATLAB version: 9.1.0.441655 (R2016b)
% -------------------------------------------------------------------
                                            

smiData = struct;
smiData.RigidTransform = struct;
smiData.RigidTransform(1).translation = ...
  [0 0 0.17500000000000004];
smiData.RigidTransform(1).angle = 0;
smiData.RigidTransform(1).axis = [0 0 0];
smiData.RigidTransform(1).ID = 'B[Base2-1:-:Link1-1]';
smiData.RigidTransform(2).translation = ...
  [-2.9210535649522895E-15 2.1925344324510107E-15 0.17499999999999982];
smiData.RigidTransform(2).angle = 0;
smiData.RigidTransform(2).axis = [0 0 0];
smiData.RigidTransform(2).ID = 'F[Base2-1:-:Link1-1]';
smiData.RigidTransform(3).translation = ...
  [0.10000000000000003 0.09699999999999992 0.61499999999999977];
smiData.RigidTransform(3).angle = 2.0943951023931953;
smiData.RigidTransform(3).axis = [0.57735026918962584 -0.57735026918962584 ...
                                  0.57735026918962584];
smiData.RigidTransform(3).ID = 'B[Link1-1:-:Link2-1]';
smiData.RigidTransform(4).translation = ...
  [0.10000000000009812 0.089999999939895159 0.61500000000013544];
smiData.RigidTransform(4).angle = 2.094395102393193;
smiData.RigidTransform(4).axis = [0.57735026918962506 -0.5773502691896274 ...
                                  0.57735026918962484];
smiData.RigidTransform(4).ID = 'F[Link1-1:-:Link2-1]';
smiData.RigidTransform(5).translation = ...
  [0.099999999999999589 0.070499999999998786 1.32];
smiData.RigidTransform(5).angle = 2.0943951023931953;
smiData.RigidTransform(5).axis = [-0.57735026918962562 -0.57735026918962562 ...
                                  -0.577350269189626];
smiData.RigidTransform(5).ID = 'B[Link2-1:-:Link3-1]';
smiData.RigidTransform(6).translation = ...
  [0.099999999999450251 0.069000000000475487 1.3199999999999223];
smiData.RigidTransform(6).angle = 2.094395102393193;
smiData.RigidTransform(6).axis = [-0.57735026918962484 -0.57735026918962706 ...
                                  -0.5773502691896254];
smiData.RigidTransform(6).ID = 'F[Link2-1:-:Link3-1]';
smiData.RigidTransform(7).translation = ...
  [0.36399999999999993 0 1.4549999999999996];
smiData.RigidTransform(7).angle = 2.0943951023931953;
smiData.RigidTransform(7).axis = [0.57735026918962584 0.57735026918962584 ...
                                  0.57735026918962584];
smiData.RigidTransform(7).ID = 'B[Link3-1:-:Link4-1]';
smiData.RigidTransform(8).translation = ...
  [0.35800000000056387 -1.8418599978531347E-12 1.4549999999972694];
smiData.RigidTransform(8).angle = 2.0943951023931953;
smiData.RigidTransform(8).axis = [0.57735026918962684 0.57735026918962562 ...
                                  0.57735026918962473];
smiData.RigidTransform(8).ID = 'F[Link3-1:-:Link4-1]';
smiData.RigidTransform(9).translation = ...
  [0.85499999999999987 -0.018500000000000183 1.4549999999999998];
smiData.RigidTransform(9).angle = 2.0943951023931953;
smiData.RigidTransform(9).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                  -0.57735026918962584];
smiData.RigidTransform(9).ID = 'B[Link4-1:-:Link5-2]';
smiData.RigidTransform(10).translation = ...
  [0.85499999999952081 -0.020499999999664453 1.4550000000005543];
smiData.RigidTransform(10).angle = 2.0943951023932028;
smiData.RigidTransform(10).axis = [-0.57735026918962817 -0.57735026918962506 ...
                                   -0.57735026918962407];
smiData.RigidTransform(10).ID = 'F[Link4-1:-:Link5-2]';
smiData.RigidTransform(11).translation = ...
  [0.90600000000000036 2.2204460492503131E-16 1.4549999999999996];
smiData.RigidTransform(11).angle = 2.094395102393197;
smiData.RigidTransform(11).axis = [-0.57735026918962462 -0.5773502691896264 ...
                                   0.5773502691896264];
smiData.RigidTransform(11).ID = 'B[Link5-2:-:Link6-1]';
smiData.RigidTransform(12).translation = ...
  [0.90600000000064485 -1.1102230246251565E-13 1.454999999999276];
smiData.RigidTransform(12).angle = 2.0943951023931975;
smiData.RigidTransform(12).axis = [-0.577350269189626 -0.57735026918962651 ...
                                   0.577350269189625];
smiData.RigidTransform(12).ID = 'F[Link5-2:-:Link6-1]';
smiData.RigidTransform(13).translation = ...
  [0.48686689172958036 0.43961046987656471 0.41484367745030015];
smiData.RigidTransform(13).angle = 0;
smiData.RigidTransform(13).axis = [0 0 0];
smiData.RigidTransform(13).ID = 'RootGround[Base2-1]';
smiData.Solid = struct;
smiData.Solid(1).mass = 0.370548340636508;
smiData.Solid(1).CoM = [855.24881515827553 -0.022650090716152725 1455.8928932143542 ...
                        ];
smiData.Solid(1).MoI = [312.661927924367 544.83068933344862 343.03009724652338 ...
                        ];
smiData.Solid(1).PoI = [-0.27280999938676542 6.0804115524008369 0.31834952527872146 ...
                        ];
smiData.Solid(1).color = [0.84313725490196079 0.84313725490196079 0.84313725490196079 ...
                          ];
smiData.Solid(1).opacity = 1;
smiData.Solid(1).ID = 'Link5*:*Default';
smiData.Solid(2).mass = 6.4434260899249747;
smiData.Solid(2).CoM = [653.53684781887137 1.1443216893334454 1455.3102038278073 ...
                        ];
smiData.Solid(2).MoI = [15763.073418740447 181989.24587795226 185621.82878778165 ...
                        ];
smiData.Solid(2).PoI = [16.086965156744821 -131.38969702415679 -1529.3923253778737 ...
                        ];
smiData.Solid(2).color = [0.84313725490196079 0.84313725490196079 0.84313725490196079 ...
                          ];
smiData.Solid(2).opacity = 1;
smiData.Solid(2).ID = 'Link4*:*Default';
smiData.Solid(3).mass = 14.576553624848922;
smiData.Solid(3).CoM = [98.590578001713212 -10.248089012548483 1436.1792741124775 ...
                        ];
smiData.Solid(3).MoI = [114721.34694412354 327159.69770911889 335930.27308899956 ...
                        ];
smiData.Solid(3).PoI = [3625.9529273477419 -19086.808367518039 -4014.3890356073339 ...
                        ];
smiData.Solid(3).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(3).opacity = 1;
smiData.Solid(3).ID = 'Link3*:*Default';
smiData.Solid(4).mass = 16.043537319681139;
smiData.Solid(4).CoM = [149.77345784798817 -0.28595107002002118 934.36926520050361 ...
                        ];
smiData.Solid(4).MoI = [651179.17776001093 640735.98600951768 88327.757613149777 ...
                        ];
smiData.Solid(4).PoI = [-2013.5808091452609 19359.590412058787 -230.19632977584965 ...
                        ];
smiData.Solid(4).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(4).opacity = 1;
smiData.Solid(4).ID = 'Link2*:*Default';
smiData.Solid(5).mass = 45.08280385879111;
smiData.Solid(5).CoM = [-94.28217371063613 0.34854902553530082 81.7549681142279 ...
                        ];
smiData.Solid(5).MoI = [904590.01497155533 1.6541055923032351E+6 2.3895967061660588E+6 ...
                        ];
smiData.Solid(5).PoI = [-560.96611437610409 24169.346153511793 5534.2191808057 ...
                        ];
smiData.Solid(5).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(5).opacity = 1;
smiData.Solid(5).ID = 'Base2*:*Default';
smiData.Solid(6).mass = 52.623469192597327;
smiData.Solid(6).CoM = [31.06709368486321 19.670362544533411 446.83041551261226 ...
                        ];
smiData.Solid(6).MoI = [2.7415086678233808E+6 1.8043393388008524E+6 2.0930490319680963E+6 ...
                        ];
smiData.Solid(6).PoI = [37826.212963763537 -372478.73183889937 114320.53321185413 ...
                        ];
smiData.Solid(6).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(6).opacity = 1;
smiData.Solid(6).ID = 'Link1*:*Default';
smiData.Solid(7).mass = 0.048898677101460244;
smiData.Solid(7).CoM = [927.277563352541 0.035247627930110985 1454.7923193273107 ...
                        ];
smiData.Solid(7).MoI = [19.286594162598561 13.865884864847111 14.076460203104004 ...
                        ];
smiData.Solid(7).PoI = [-0.017469082788617307 0.0697641019541301 -0.022066403594452798 ...
                        ];
smiData.Solid(7).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(7).opacity = 1;
smiData.Solid(7).ID = 'Link6*:*Default';
smiData.RevoluteJoint = struct;
smiData.RevoluteJoint(1).Rz = struct;
smiData.RevoluteJoint(1).Rz.Pos = 170.04417756877979;
smiData.RevoluteJoint(1).ID = '[Base2-1:-:Link1-1]';
smiData.RevoluteJoint(2).Rz = struct;
smiData.RevoluteJoint(2).Rz.Pos = -9.8014835876610356;
smiData.RevoluteJoint(2).ID = '[Link1-1:-:Link2-1]';
smiData.RevoluteJoint(3).Rz = struct;
smiData.RevoluteJoint(3).Rz.Pos = -12.265740028995907;
smiData.RevoluteJoint(3).ID = '[Link2-1:-:Link3-1]';
smiData.RevoluteJoint(4).Rz = struct;
smiData.RevoluteJoint(4).Rz.Pos = -58.745248396211259;
smiData.RevoluteJoint(4).ID = '[Link3-1:-:Link4-1]';
smiData.RevoluteJoint(5).Rz = struct;
smiData.RevoluteJoint(5).Rz.Pos = 9.67450522856515;
smiData.RevoluteJoint(5).ID = '[Link4-1:-:Link5-2]';
smiData.RevoluteJoint(6).Rz = struct;
smiData.RevoluteJoint(6).Rz.Pos = -75.733346756146432;
smiData.RevoluteJoint(6).ID = '[Link5-2:-:Link6-1]';

